### PR TITLE
finishing password reset

### PR DESCRIPTION
**Pull request by JeanIrad**
# Password reset

##Password Reset

Describe the purpose of the PR

## Changes Made

Describe the changes made

## Testing Instructions

List all testing instruction, if availbale

## Related Issues

Lists all related issues

## Checklist

Please review the following checklist and make sure all tasks are complete before submitting:

- [ ] Code follows the project's coding standards
- [ ] Changes are covered by tests
- [ ] Documentation is updated (if applicable)
- [ ] All tests pass

### CODE REVIEW

**Review by Favor-star — APPROVED** [review]
Looks good to me!

**Review by hozayves — CHANGES_REQUESTED** [review]
Hey Jado,

I have a quick suggestion. 
- Could you please remove the toastContainer from ResentPassword.tsx? It's already configured in App.tsx, so having it here seems redundant. You can refer to how Ange used react-toastify in LoginComponent.tsx for guidance.
- Let us know why you made changes in footer component
-  and also your forgot password component is too much wider than usual on big screen. look on the way you can make it look good instead 50%
Screenshot 2024-06-22 at 16 36 46



Thanks!

**Comment by JeanIrad** [comment]
> Hey Jado,
> 
> I have a quick suggestion.
> 
> * Could you please remove the toastContainer from ResentPassword.tsx? It's already configured in App.tsx, so having it here seems redundant. You can refer to how Ange used react-toastify in LoginComponent.tsx for guidance.
> * Let us know why you made changes in footer component
> * and also your forgot password component is too much wider than usual on big screen. look on the way you can make it look good instead 50%
> 
> Screenshot 2024-06-22 at 16 36 46
> Thanks!

I believe the same too

**Comment by JeanIrad** [comment]
> > Hey Jado,
> > I have a quick suggestion.
> > 
> > * Could you please remove the toastContainer from ResentPassword.tsx? It's already configured in App.tsx, so having it here seems redundant. You can refer to how Ange used react-toastify in LoginComponent.tsx for guidance.
> > * Let us know why you made changes in footer component
> > * and also your forgot password component is too much wider than usual on big screen. look on the way you can make it look good instead 50%
> > 
> > Screenshot 2024-06-22 at 16 36 46
> > Thanks!
> 
> I believe the same too

I also refactored it

**Review by amin-leon — CHANGES_REQUESTED** [review]
You got conflicts in app.tsx

**Comment by JeanIrad** [comment]
> You got conflicts in app.tsx

I have rebased, you can check again

**Review by patrickhag — APPROVED** [review]
👌

**Review by princenzmw — APPROVED** [review]

**Review by amin-leon — APPROVED** [review]

**Review by hozayves — APPROVED** [review]

**Review by niyontwali — APPROVED** [review]

**Pull request merged**
